# https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: Build & Watch
    init: npm install --include=dev
    command: npm run build -- -w -f

  - name: Node
    init: npm install --include=dev
    command: npm start node -- --no-watch -l

  - name: Next.js
    init: npm install --include=dev
    command: npm start next -- --no-watch -l

  - name: Vanilla
    init: npm install --include=dev
    command: npm start vanilla -- --no-watch -l
