# This workflow will install Uglify and verify that fabric can be build with it

name: PR Quality Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uglyfied build
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run lint
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create comment pre
      if: ${{ github.event.action != 'closed' }}
      id: create-comment-pre
      uses: actions/github-script@v6
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BASE_BRANCH: master
        GIT_SCOPE: fabricjs
        REPO: fabric.js
        # pass test context
        CONTEXT_NAMES: 'node, chrome, firefox'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
            const { PR_NUMBER, BASE_BRANCH, GIT_SCOPE, REPO } = process.env;
            const contextNames = process.env.CONTEXT_NAMES.split(',').map(val => val.trim());
            const urls = contextNames.map(c => {
              const testBranchName = `ci-pr%23${PR_NUMBER}-visuals-${c}`;
              return `[${c}](https://github.com/${GIT_SCOPE}/${REPO}/compare/${BASE_BRANCH}...${testBranchName})`
            });
            return `**Visual Test Result Diffs**: ${urls.join(', ')}`;
    - name: Code Coverage Report Updater
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build -- -f
    - run: npm run test:coverage 
    - run: npm run coverage:report
    - uses: ShaMan123/lcov-reporter-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        delete-old-comments: true
        update-comment: true
        comment_prepend: ${{ steps.create-comment-pre.outputs.result || '' }}

