# This workflow will install Uglify and verify that fabric can be build with it

name: PR Quality Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uglyfied build
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run lint
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Code Coverage Report Updater
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build -- -f
    - run: npm run test:coverage 
    - run: npm run coverage:report
    - uses: ShaMan123/lcov-reporter-action@v1.1.1
      # env:
        # COMPARE_BASE_URL: '[{1}](https://github.com/fabricjs/fabric.js/compare/{0}...ci-pr%23${{ github.event.pull_request.number }}-visuals-{1}'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        delete-old-comments: true
        update-comment: true
        comment_prepend: '**Visual Test Results**: ${{ env.COMPARE_BASE_URL }}'

