name: '🧪'
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  browser:
    name: browser tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build -- -f
      - name: Run browser headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test -- -c chrome firefox -s unit visual
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cli_output/test_results
  node:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node-version }} ${{ matrix.suite }} tests
    strategy:
      fail-fast: false
      matrix:
        # For more information see:
        # https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
        # supported Node.js release schedule: https://nodejs.org/en/about/releases/
        node-version: [14, 16, 18]
    env:
      flag: ${{ (matrix.node-version == 16 && '--coverage') || '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install node-canvas
        run: sudo apt-get install libgif-dev libpng-dev libpango1.0-dev libjpeg8-dev librsvg2-dev libcairo2-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}.x
          cache: npm
      - run: npm ci
      - run: npm run build -- -f
      - name: Run tests
        run: npm run test -- -c node -a ${{ env.flag }}
      - name: Prepare Coverage Report
        if: matrix.node-version == 16 && always()
        run: npm run coverage:report
      - name: Post Coverage Report
        if: matrix.node-version == 16 && always()
        uses: ShaMan123/lcov-reporter-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
          update-comment: true
      - name: Rename artifact (*node > *node${{ matrix.node-version }})
        if: always()
        run: |
          mv cli_output/test_results/visual/node cli_output/test_results/visual/node${{ matrix.node-version }}
          mv cli_output/test_results/visual/node.txt cli_output/test_results/visual/node${{ matrix.node-version }}.txt
          mv cli_output/test_results/unit/node.txt cli_output/test_results/unit/node${{ matrix.node-version }}.txt
      - name: Archive visual test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cli_output/test_results
