name: '🧪'
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Upload build artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build -- -f
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: tests-build
          path: dist
  browser:
    name: browser tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: tests-build
          path: dist
      - name: Run browser headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test -- -c chrome firefox -s unit visual
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: browser-test-results
          path: cli_output/test_results
  node:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node-version }} ${{ matrix.suite }} tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        # For more information see:
        # https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
        # supported Node.js release schedule: https://nodejs.org/en/about/releases/
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install node-canvas
        run: sudo apt-get install libgif-dev libpng-dev libpango1.0-dev libjpeg8-dev librsvg2-dev libcairo2-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: tests-build
          path: dist
      - name: Run tests
        run: npm run test -- -c node -a
      - name: Archive visual test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: node-${{ matrix.node-version }}-test-results
          path: cli_output/test_results
  cleanup:
    runs-on: ubuntu-latest
    name: Delete build artifacts
    needs: [build, browser, node]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: tests-build
