name: '🧪'
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Upload build artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build -- -f
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
  browser:
    name: ${{ matrix.target }} ${{ matrix.suite }} tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16.x]
        target: [chrome, firefox]
        suite: [unit, visual]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: Run ${{ matrix.target }} ${{ matrix.suite }} headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test -- -c ${{ matrix.target }} -s ${{ matrix.suite }}
      - name: Archive visual test results
        if: failure() && matrix.suite == 'visual'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-failing-visual-tests
          path: cli_output/test_results/visuals
  node:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node-version }} ${{ matrix.suite }} tests
    strategy:
      fail-fast: false
      matrix:
        # For more information see:
        # https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
        # supported Node.js release schedule: https://nodejs.org/en/about/releases/
        node-version: [14.x, 16.x, 18.x]
        suite: [unit, visual]
    steps:
      - uses: actions/checkout@v2
      - name: Install node-canvas
        run: sudo apt-get install libgif-dev libpng-dev libpango1.0-dev libjpeg8-dev librsvg2-dev libcairo2-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: Run ${{ matrix.suite }} tests
        run: npm run test -- -c node -s ${{ matrix.suite }}
      - name: Archive visual test results
        if: failure() && matrix.suite == 'visual' && matrix.node-version == '16.x'
        uses: actions/upload-artifact@v3
        with:
          name: node-failing-visual-tests
          path: cli_output/test_results/visuals
