name: '🏷️'

on:
  push:
    branches:
      - master
      - ci-prerelease

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release on Push
        uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: norelease
