# This workflow will do a clean install of node dependencies, build the library, run testem visual tests for Chrome

name: Visual unit tests on Chrome

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  chrome-visual-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Visual unit tests on Chrome
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build -- -f -x gestures,accessors
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test -- -p 8080 -c chrome -r -f visual/clippath.js
    - name: Commit Results
      uses: EndBug/add-and-commit@v9.1.0
      with:
        add: ./test/visual/golden
        new_branch: ci-pr#${{ github.event.pull_request.number }}-visuals-chrome
        push: git push -u origin ci-pr#${{ github.event.pull_request.number }}-visuals-chrome
